2018-10-12 23:43:44,882 ERROR: Exception on / [GET] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/app/routes.py", line 40, in index
    posts=posts.items, next_url=bnext_url,
NameError: name 'bnext_url' is not defined
2018-10-12 23:44:28,890 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-13 00:17:39,878 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-13 00:18:22,613 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-13 11:30:22,889 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-14 15:20:37,269 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-14 15:21:09,694 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-14 15:23:12,199 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-14 15:23:55,547 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-14 15:27:14,164 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
2018-10-14 16:27:21,451 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
2018-10-14 16:28:03,482 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
2018-10-14 16:32:04,344 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
2018-10-14 16:39:37,369 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 16:39:43,406 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 16:40:05,408 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 18:49:18,895 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 18:49:23,277 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 18:50:03,689 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 18:50:38,468 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 18:50:51,573 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 18:51:34,839 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 18:51:38,092 ERROR: Exception on /reset_password_request [GET] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/evh111/Desktop/programz/petblog/app/routes.py", line 172, in reset_password_request
    title='Reset Password', form=form)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/evh111/Desktop/programz/petblog/app/templates/reset_password_request.html", line 3, in template
    {% block content }
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/parser.py", line 257, in parse_block
    node.name = self.stream.expect('name').value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/lexer.py", line 388, in expect
    next(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/lexer.py", line 359, in __next__
    self.current = next(self._iter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/lexer.py", line 562, in wrap
    for lineno, token, value in stream:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/lexer.py", line 683, in tokeniter
    filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
2018-10-14 18:54:12,146 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 18:55:45,087 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 19:04:39,974 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 19:14:29,190 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 19:17:09,292 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 19:22:33,970 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 19:23:39,253 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:48]
2018-10-14 19:38:00,204 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:53]
2018-10-14 19:38:38,230 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:53]
2018-10-14 19:39:33,379 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-14 19:44:19,300 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-14 19:47:58,638 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-14 23:38:33,948 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-14 23:41:04,437 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-14 23:42:46,484 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:47]
2018-10-15 14:10:15,819 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
