2018-10-15 14:10:18,935 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
2018-10-15 14:13:47,267 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
2018-10-15 14:16:53,355 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
2018-10-15 20:47:27,629 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
2018-10-15 20:49:36,887 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
2018-10-15 20:52:44,221 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
2018-10-15 21:03:25,667 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
2018-10-15 21:48:57,446 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:49]
2018-10-16 18:45:41,984 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:51]
2018-10-17 21:04:10,641 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:55]
2018-10-17 21:18:05,752 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:55]
2018-10-17 21:23:45,024 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:55]
2018-10-18 16:45:09,453 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:55]
2018-10-18 16:49:23,172 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:55]
2018-10-18 16:49:42,792 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:55]
2018-10-18 16:52:36,582 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:55]
2018-10-19 17:10:18,113 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:55]
2018-10-19 17:10:33,248 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:55]
2018-10-19 19:49:26,168 INFO: PetBlog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:55]
2018-10-21 20:16:12,289 INFO: PetBlog startup[in /Users/evh111/Desktop/programz/petblog/app/__init__.py:76]
2018-10-21 20:16:35,289 ERROR: Exception on / [GET][in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/app/main/routes.py", line 45, in index
    prev_url=prev_url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/evh111/Desktop/programz/petblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/evh111/Desktop/programz/petblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/Users/evh111/Desktop/programz/petblog/app/templates/base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">PetBlog</a>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
